### ISSUE TITLE
perlmodule sig11 on osx

### ISSUE THREAD

**Issue by eam** [eam/libcrange#7]
/tmp/range.conf:
dns_data_file=/Users/evan/prefix/etc/dns_data.tinydns
yst_ip_list=/Users/evan/prefix/etc/yst-ip-list
yaml_path=/Users/evan/prefix/rangedata
loadmodule /Users/evan/prefix/usr/lib/libcrange/yamlfile
loadmodule /Users/evan/prefix/usr/lib/libcrange/ip
loadmodule /Users/evan/prefix/usr/lib/libcrange/yst-ip-list
perl_inc_path=/Users/evan/prefix/usr/local/lib64/perl5:/Users/evan/prefix/var/libcrange/perl:/Users/evan/prefix/usr/local/lib/perl/5.14.2
perlmodule LibrangeUtils
perlmodule LibrangeAdminscf

The last two lines, or seemingly any perlmodule use, causes the crash.

(gdb) run -c /tmp/range.conf foo100..1
Starting program: /Users/evan/prefix/usr/bin/crange -c /tmp/range.conf foo100..1
Reading symbols for shared libraries +++++++.......................... done
Reading symbols for shared libraries ... done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x000000000000000c
0x00000001000d4b32 in Perl_sv_replace ()
(gdb) bt
#0  0x00000001000d4b32 in Perl_sv_replace ()
#1  0x00000001000ec843 in Perl_leave_scope ()
#2  0x0000000100062486 in Perl_newATTRSUB ()
#3  0x00000001000681a2 in Perl_call_pv ()
#4  0x000000010000879c in get_exported_functions [inlined]() at /Users/evan/git/libcrange/source/src/perl_functions.c:61
#5  0x000000010000879c in add_functions_from_perlmodule (lr=0x100813020, pool=0x7fff5fbff390, perlfunctions=0x7fff5fbff390, module=0x7fff5fbff390 "???_?", prefix=0x7fff5fbff390 "???_?") at perl_functions.c:134
#6  0x000000010000a226 in parse_config_file [inlined]() at /Users/evan/git/libcrange/source/src/libcrange.c:430
#7  0x000000010000a226 in libcrange_new (pool=0x10000f198, config_file=0x7fff5fbff49b "LibrangeUtils") at libcrange.c:65
#8  0x0000000100000c9f in main (argc=4, argv=0x7fff5fbffa38) at main.c:55

**Comment by eam** [comment]
Fixed by avoiding /usr/bin/perl on OSX. Brewperl works fine.
